#!/bin/sh

# 目标名检查
target=$1
if [ -z ${target} ]; then
    echo "Error: missing the target name"
    exit
fi

argv=$3

# 排除目录检查
exclude_dir=$2
if [ ! -z ${exclude_dir} ]; then
    if [ ${exclude_dir} = '-b' ]; then
        argv='-b';
    elif [ ! -d ${exclude_dir} ]; then
        echo "Error: can not find '${exclude_dir}' to be exclude dir!"
        exit
    fi
fi

# 设置CMake 构建目录
build_dir=../build/
# 查找 .gcda 与 .gcno 文件
object_dir=`find ${build_dir} -type d -name ${target}.dir`
if [ -z ${object_dir} ]; then
    echo "Error: can not find '${target}' to be target!"
    exit
fi

if [ ! -d "obj" ]; then
    mkdir obj
fi

for file in `find ${object_dir} -type f -name *.gc*`
do
    cp ${file} ./obj
done

source_dir=../src/

# 设置排除目录参数
excludeArg=''
if [ ! -z ${exclude_dir} ]; then
    excludeArg="--exclude=${exclude_dir}"
fi

gcovr ./obj/ --root=${source_dir} ${excludeArg} ${argv}

rm -rf obj/